#include "render/device/dx12/dx12.h"

#include "core/debug.h"

#include "render/utils.h"

#include <D3Dcompiler.h>

namespace render {
	
	namespace utils {

		bool IsTransitionAllowed(D3D12_COMMAND_LIST_TYPE commandlistType, D3D12_RESOURCE_STATES state)
		{
			constexpr int VALID_COMPUTE_QUEUE_RESOURCE_STATES =
				D3D12_RESOURCE_STATE_COMMON
				| D3D12_RESOURCE_STATE_UNORDERED_ACCESS
				| D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE
				| D3D12_RESOURCE_STATE_COPY_DEST
				| D3D12_RESOURCE_STATE_COPY_SOURCE
				| D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT;

			constexpr int VALID_COPY_QUEUE_RESOURCE_STATES =
				D3D12_RESOURCE_STATE_COMMON
				| D3D12_RESOURCE_STATE_COPY_DEST
				| D3D12_RESOURCE_STATE_COPY_SOURCE;

			if (commandlistType == D3D12_COMMAND_LIST_TYPE_COMPUTE)
			{
				return (state & VALID_COMPUTE_QUEUE_RESOURCE_STATES) == state;
			}
			else if (commandlistType == D3D12_COMMAND_LIST_TYPE_COPY)
			{
				return (state & VALID_COPY_QUEUE_RESOURCE_STATES) == state;
			}
			return true;
		}

		string ResourceStateToString(D3D12_RESOURCE_STATES state)
		{
			switch (state)
			{
			case D3D12_RESOURCE_STATE_PRESENT: return "Present";
			case D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER: return "Vertex_Constant_Buffer";
			case D3D12_RESOURCE_STATE_INDEX_BUFFER: 
			case D3D12_RESOURCE_STATE_RENDER_TARGET:				
			case D3D12_RESOURCE_STATE_UNORDERED_ACCESS:
			case D3D12_RESOURCE_STATE_DEPTH_WRITE:
			case D3D12_RESOURCE_STATE_DEPTH_READ:
			case D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE:
			case D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE:
			case D3D12_RESOURCE_STATE_STREAM_OUT:
			case D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT:
			case D3D12_RESOURCE_STATE_COPY_DEST:
			case D3D12_RESOURCE_STATE_COPY_SOURCE:
			case D3D12_RESOURCE_STATE_RESOLVE_DEST:
			case D3D12_RESOURCE_STATE_RESOLVE_SOURCE:
			case D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE:
			case D3D12_RESOURCE_STATE_SHADING_RATE_SOURCE:
			case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_8000:
			case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_4000:
			case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_100000:
			case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_40000000:
			case D3D12_RESOURCE_STATE_RESERVED_INTERNAL_80000000:
			case D3D12_RESOURCE_STATE_GENERIC_READ:
			case D3D12_RESOURCE_STATE_ALL_SHADER_RESOURCE:			
			//case D3D12_RESOURCE_STATE_PREDICATION:
			case D3D12_RESOURCE_STATE_VIDEO_DECODE_READ:
			case D3D12_RESOURCE_STATE_VIDEO_DECODE_WRITE:
			case D3D12_RESOURCE_STATE_VIDEO_PROCESS_READ:
			case D3D12_RESOURCE_STATE_VIDEO_PROCESS_WRITE:
			case D3D12_RESOURCE_STATE_VIDEO_ENCODE_READ:
			case D3D12_RESOURCE_STATE_VIDEO_ENCODE_WRITE:
			default:
				ASSERT(false);
				break;
			}
			return "Unknown";
		}

		string CommandlistTypeToString(D3D12_COMMAND_LIST_TYPE type)
		{
			switch (type)
			{
			case D3D12_COMMAND_LIST_TYPE_DIRECT: return "Direct";
			case D3D12_COMMAND_LIST_TYPE_BUNDLE: return "Bundle";
			case D3D12_COMMAND_LIST_TYPE_COMPUTE: return "Compute";
			case D3D12_COMMAND_LIST_TYPE_COPY: return "Copy";
			case D3D12_COMMAND_LIST_TYPE_VIDEO_DECODE: return "VideoDecode";
			case D3D12_COMMAND_LIST_TYPE_VIDEO_PROCESS: return "VideoProcess";
			case D3D12_COMMAND_LIST_TYPE_VIDEO_ENCODE: return "VideoEncode";
			case D3D12_COMMAND_LIST_TYPE_NONE: return "None";
			default:
				ASSERT(false);
				break;
			}
			return "Unknown";
		}
	}
}
